server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

metrics_generator:
  processor:
    service_graphs: {}
  storage:
    path: /tmp/tempo/generator/wal
  registry:
    external_labels:
      source: tempo
  remote_write:
    - url: http://prometheus:9090/api/v1/write

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
