-- ============================================================
-- FieldTrack 2.0 — Complete Production Schema Baseline
-- ============================================================
-- This file represents the ENTIRE live Supabase database schema
-- as of Phase 28 (2026-03-25).
--
-- Generated by diffing the live Supabase project nvezwhasasykwnnblokk
-- against the Phase 27b document. All divergences resolved.
--
-- This migration can be run on a blank Supabase project to
-- recreate the exact schema without any data.
--
-- Ordering:
-- 1. Extensions
-- 2. Enums
-- 3. Sequences
-- 4. Tables (no FKs)
-- 5. Indexes
-- 6. Functions
-- 7. Triggers
-- 8. RLS Policies
-- 9. Cron Jobs
-- ============================================================

-- ══════════════════════════════════════════════════════════════
-- EXTENSIONS
-- ══════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_cron";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- ══════════════════════════════════════════════════════════════
-- ENUMS
-- ══════════════════════════════════════════════════════════════

CREATE TYPE IF NOT EXISTS public.user_role AS ENUM ('ADMIN', 'EMPLOYEE');
CREATE TYPE IF NOT EXISTS public.expense_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE IF NOT EXISTS public.distance_job_status AS ENUM ('pending', 'processing', 'done', 'failed');

-- ══════════════════════════════════════════════════════════════
-- SEQUENCES
-- ══════════════════════════════════════════════════════════════

CREATE SEQUENCE IF NOT EXISTS public.employee_code_seq
  START WITH 1 INCREMENT BY 1 NO CYCLE;

-- ══════════════════════════════════════════════════════════════
-- TABLES (Core)
-- ══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.organizations (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT        NOT NULL,
  slug       TEXT        UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.organizations IS
  'Top-level tenant. All other tables scope to organization_id.';

CREATE TABLE IF NOT EXISTS public.users (
  id              UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID             NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  email           TEXT             NOT NULL UNIQUE,
  role            public.user_role NOT NULL,
  created_at      TIMESTAMPTZ      NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ      NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.users IS
  'Application user profiles linked to auth.users via shared UUID and email.';

CREATE TABLE IF NOT EXISTS public.employees (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id          UUID        UNIQUE REFERENCES public.users(id) ON DELETE SET NULL,
  name             TEXT        NOT NULL,
  phone            TEXT,
  is_active        BOOLEAN     NOT NULL DEFAULT true,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- NOTE: column order matches live DB (employee_code and last_activity_at were added later)
  employee_code    TEXT        NOT NULL UNIQUE,
  last_activity_at TIMESTAMPTZ
);

COMMENT ON TABLE public.employees IS
  'Field employees. One row per employee across organization.';
COMMENT ON COLUMN public.employees.employee_code IS
  'Human-readable identifier e.g. EMP0001. Generated by sequence.';
COMMENT ON COLUMN public.employees.last_activity_at IS
  'Updated on check-in / check-out. Used to compute ACTIVE / RECENT / INACTIVE status.';

CREATE TABLE IF NOT EXISTS public.attendance_sessions (
  id                            UUID                       PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id               UUID                       NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id                   UUID                       NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  checkin_at                    TIMESTAMPTZ                NOT NULL DEFAULT now(),
  checkout_at                   TIMESTAMPTZ,
  distance_recalculation_status public.distance_job_status NOT NULL DEFAULT 'pending',
  total_distance_km             FLOAT8,
  total_duration_seconds        INT,
  created_at                    TIMESTAMPTZ                NOT NULL DEFAULT now(),
  updated_at                    TIMESTAMPTZ                NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.attendance_sessions IS
  'One row per field session (check-in to check-out). Source for GPS trails and distance jobs.';

CREATE TABLE IF NOT EXISTS public.gps_locations (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  session_id      UUID        NOT NULL REFERENCES public.attendance_sessions(id) ON DELETE CASCADE,
  employee_id     UUID        NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  latitude        FLOAT8      NOT NULL CHECK (latitude  >= -90  AND latitude  <= 90),
  longitude       FLOAT8      NOT NULL CHECK (longitude >= -180 AND longitude <= 180),
  accuracy        FLOAT8,
  recorded_at     TIMESTAMPTZ NOT NULL,
  sequence_number INT,
  is_duplicate    BOOLEAN     NOT NULL DEFAULT false,
  UNIQUE (session_id, recorded_at)
);

COMMENT ON TABLE public.gps_locations IS
  'Raw GPS breadcrumb trail per session. Duplicate flag set by distance calculation job.
   Phase 27b: Added sequence_number field for monotonic ordering validation.';

CREATE TABLE IF NOT EXISTS public.expenses (
  id                UUID                  PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id   UUID                  NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id       UUID                  NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  amount            NUMERIC               NOT NULL CHECK (amount > 0),
  description       TEXT                  NOT NULL,
  status            public.expense_status NOT NULL DEFAULT 'PENDING',
  receipt_url       TEXT,
  submitted_at      TIMESTAMPTZ           NOT NULL DEFAULT now(),
  reviewed_at       TIMESTAMPTZ,
  reviewed_by       UUID                  REFERENCES public.users(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ           NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ           NOT NULL DEFAULT now(),
  rejection_comment TEXT
);

COMMENT ON TABLE public.expenses IS
  'Employee expense reports with approval workflow.
   Phase 27b: Added rejection_comment field for admin feedback.';

CREATE TABLE IF NOT EXISTS public.session_summaries (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id        UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  session_id             UUID        NOT NULL UNIQUE REFERENCES public.attendance_sessions(id) ON DELETE CASCADE,
  total_distance_km      FLOAT8      NOT NULL DEFAULT 0,
  total_duration_seconds INT         NOT NULL DEFAULT 0,
  avg_speed_kmh          FLOAT8      NOT NULL DEFAULT 0,
  computed_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.session_summaries IS
  'Computed distance/duration/speed per session. Written by BullMQ distance recalculation job.';

CREATE TABLE IF NOT EXISTS public.admin_sessions (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id        UUID        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  organization_id UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  started_at      TIMESTAMPTZ NOT NULL,
  ended_at        TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.admin_sessions IS
  'Tracks when an admin started/stopped monitoring employees. Audit and compliance trail.';

CREATE TABLE IF NOT EXISTS public.employee_daily_metrics (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id      UUID        NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  date             DATE        NOT NULL,
  sessions         INT         NOT NULL DEFAULT 0,
  distance_km      FLOAT8      NOT NULL DEFAULT 0,
  duration_seconds INT         NOT NULL DEFAULT 0,
  expenses_count   INT         NOT NULL DEFAULT 0,
  expenses_amount  NUMERIC     NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_employee_daily_metrics UNIQUE (employee_id, date)
);

COMMENT ON TABLE public.employee_daily_metrics IS
  'Pre-aggregated daily metrics per employee. Powers leaderboards and analytics dashboards.
   Upserted by API on checkout and expense submission.';

CREATE TABLE IF NOT EXISTS public.org_daily_metrics (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id        UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  date                   DATE        NOT NULL,
  total_sessions         INT         NOT NULL DEFAULT 0,
  total_distance_km      FLOAT8      NOT NULL DEFAULT 0,
  total_duration_seconds INT         NOT NULL DEFAULT 0,
  active_employees       INT         NOT NULL DEFAULT 0,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_org_daily_metrics UNIQUE (organization_id, date)
);

COMMENT ON TABLE public.org_daily_metrics IS
  'Pre-aggregated daily metrics per organization. Powers org-level trend charts.
   Rolled up from employee_daily_metrics by API.';

CREATE TABLE IF NOT EXISTS public.employee_latest_sessions (
  employee_id            UUID        PRIMARY KEY REFERENCES public.employees(id) ON DELETE CASCADE,
  organization_id        UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  session_id             UUID        REFERENCES public.attendance_sessions(id) ON DELETE SET NULL,
  latest_checkin         TIMESTAMPTZ,
  latest_checkout        TIMESTAMPTZ,
  total_distance_km      FLOAT8,
  total_duration_seconds INT,
  status                 TEXT        CHECK (status IN ('ACTIVE', 'RECENT', 'INACTIVE')),
  updated_at             TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.employee_latest_sessions IS
  'Snapshot of each employee''s latest session state. Source of truth for dashboard reads.
   NEVER scan attendance_sessions for dashboard queries — read from here instead.
   Status lifecycle: ACTIVE (trigger) → RECENT (trigger) → INACTIVE (pg_cron hourly).';

-- ══════════════════════════════════════════════════════════════
-- TABLES (Webhooks)
-- ══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.webhooks (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  url             TEXT        NOT NULL,
  secret          TEXT        NOT NULL,
  events          TEXT[]      NOT NULL DEFAULT '{}',
  is_active       BOOLEAN     NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
  -- NOTE: no updated_at in live DB — webhooks are replaced, not updated
);

COMMENT ON TABLE public.webhooks IS
  'Webhook configuration per organization.
   Events: Array of strings (e.g., INVOICE_GENERATED, REPORT_READY).
   secret: used for HMAC-SHA256 signature verification.
   ⚠️  secret is stored in plain text. Future improvement: move to Supabase Vault
   (vault.create_secret) or store only a bcrypt hash, never the raw value.';

-- ── webhook_deliveries ──────────────────────────────────────
-- Live schema is significantly richer than the Phase 25 doc.
-- Key changes vs doc:
--   + organization_id (for RLS scoping)
--   + event_id UUID (idempotency key — unique per event+webhook)
--   + status TEXT with 'pending' default (replaces status_code INT)
--   + response_status INT / response_body TEXT / last_error TEXT
--     (replace status_code INT / response TEXT / error TEXT)
--   + delivered_at TIMESTAMPTZ (replaces updated_at)
--   - updated_at removed
--   - max_retries removed (retry logic now in BullMQ)
CREATE TABLE IF NOT EXISTS public.webhook_deliveries (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  webhook_id      UUID        NOT NULL REFERENCES public.webhooks(id) ON DELETE CASCADE,
  organization_id UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  event_id        UUID        NOT NULL,
  event_type      TEXT        NOT NULL,
  payload         JSONB       NOT NULL,
  status          TEXT        NOT NULL DEFAULT 'pending',
  attempts        INT         NOT NULL DEFAULT 0,
  response_status INT,
  response_body   TEXT,
  last_error      TEXT,
  next_retry_at   TIMESTAMPTZ,
  delivered_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (event_id, webhook_id)
);

COMMENT ON TABLE public.webhook_deliveries IS
  'Webhook delivery attempts and status tracking.
   status: pending | delivered | failed
   event_id: idempotency key — one delivery record per (event, webhook) pair.
   Retry logic handled by BullMQ worker (exponential backoff).';

-- ══════════════════════════════════════════════════════════════
-- TABLES (Queue & Dashboard)
-- ══════════════════════════════════════════════════════════════

-- ── queue_retry_intents ──────────────────────────────────────
-- Live schema differs from Phase 21 doc:
--   + job_key TEXT (replaces job_id TEXT)
--   + payload JSONB (new — stores job data for re-enqueue)
--   + status TEXT with 'pending' default (new)
--   - job_id removed
--   - max_retries removed
--   Unique constraint: (queue_name, job_key)
CREATE TABLE IF NOT EXISTS public.queue_retry_intents (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  queue_name    TEXT        NOT NULL,
  job_key       TEXT        NOT NULL,
  payload       JSONB       NOT NULL,
  status        TEXT        NOT NULL DEFAULT 'pending',
  retry_count   INT         NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  error_message TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (queue_name, job_key)
);

COMMENT ON TABLE public.queue_retry_intents IS
  'BullMQ job retry tracking per queue.
   job_key: stable deduplication key per logical job (e.g., session UUID).
   payload: stored for re-enqueue without recomputing.
   status: pending | retrying | exhausted | succeeded';

-- ── org_dashboard_snapshot ───────────────────────────────────
-- Live schema is significantly richer than the Phase 24 doc.
-- Key changes vs doc:
--   - id UUID column removed — organization_id IS the PK
--   - total_employees, active_today, total_distance_today, total_expenses_today removed
--   + active_employee_count, recent_employee_count, inactive_employee_count (status breakdown)
--   + active_employees_today, today_session_count, today_distance_km
--   + pending_expense_count, pending_expense_amount
--   - snapshot_updated_at, created_at removed; only updated_at remains
CREATE TABLE IF NOT EXISTS public.org_dashboard_snapshot (
  organization_id        UUID    PRIMARY KEY REFERENCES public.organizations(id) ON DELETE CASCADE,
  active_employee_count  INT     NOT NULL DEFAULT 0,
  recent_employee_count  INT     NOT NULL DEFAULT 0,
  inactive_employee_count INT    NOT NULL DEFAULT 0,
  active_employees_today INT     NOT NULL DEFAULT 0,
  today_session_count    INT     NOT NULL DEFAULT 0,
  today_distance_km      FLOAT8  NOT NULL DEFAULT 0,
  pending_expense_count  INT     NOT NULL DEFAULT 0,
  pending_expense_amount NUMERIC NOT NULL DEFAULT 0,
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.org_dashboard_snapshot IS
  'Cached dashboard metrics for org home screen.
   organization_id is the PK — one row per org.
   Updated incrementally by API on checkout / expense events.
   Columns reflect the richer Phase 28 dashboard design.';

-- ══════════════════════════════════════════════════════════════
-- INDEXES
-- ══════════════════════════════════════════════════════════════

-- users
CREATE INDEX IF NOT EXISTS idx_users_org
  ON public.users (organization_id);

-- employees
CREATE INDEX IF NOT EXISTS idx_employees_org
  ON public.employees (organization_id);
CREATE INDEX IF NOT EXISTS idx_employees_user
  ON public.employees (user_id);
CREATE INDEX IF NOT EXISTS idx_employees_code
  ON public.employees (employee_code);

-- attendance_sessions
CREATE INDEX IF NOT EXISTS idx_sessions_employee
  ON public.attendance_sessions (employee_id);
CREATE INDEX IF NOT EXISTS idx_sessions_org_employee
  ON public.attendance_sessions (organization_id, employee_id);
CREATE INDEX IF NOT EXISTS idx_sessions_org_time
  ON public.attendance_sessions (organization_id, checkin_at);
CREATE INDEX IF NOT EXISTS idx_sessions_org_emp_checkin
  ON public.attendance_sessions (organization_id, employee_id, checkin_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_active_session
  ON public.attendance_sessions (employee_id) WHERE checkout_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_sessions_requeue
  ON public.attendance_sessions (checkout_at)
  WHERE checkout_at IS NOT NULL
    AND distance_recalculation_status IN ('pending', 'failed');

-- gps_locations
CREATE INDEX IF NOT EXISTS idx_locations_org
  ON public.gps_locations (organization_id);
CREATE INDEX IF NOT EXISTS idx_locations_session_time
  ON public.gps_locations (session_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_locations_session_sequence
  ON public.gps_locations (session_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_locations_employee_time
  ON public.gps_locations (employee_id, recorded_at);
-- Phase 27b: composite index for O(log n) route-playback queries
-- NOTE: no CONCURRENTLY — not allowed inside Supabase migration transactions
CREATE INDEX IF NOT EXISTS idx_gps_locations_session_recorded_at
  ON public.gps_locations (session_id, recorded_at ASC);

-- expenses
CREATE INDEX IF NOT EXISTS idx_expenses_employee
  ON public.expenses (employee_id);
CREATE INDEX IF NOT EXISTS idx_expenses_status
  ON public.expenses (status);
CREATE INDEX IF NOT EXISTS idx_expenses_org_status
  ON public.expenses (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_expenses_org_submitted
  ON public.expenses (organization_id, submitted_at);
CREATE INDEX IF NOT EXISTS idx_expenses_org_employee
  ON public.expenses (organization_id, employee_id);
-- Live DB extra: supports FK lookup for reviewed_by audits
CREATE INDEX IF NOT EXISTS idx_expenses_reviewed_by
  ON public.expenses (reviewed_by);

-- session_summaries
CREATE INDEX IF NOT EXISTS idx_summaries_org
  ON public.session_summaries (organization_id);
CREATE INDEX IF NOT EXISTS idx_summaries_session
  ON public.session_summaries (session_id);
CREATE INDEX IF NOT EXISTS idx_summaries_org_computed
  ON public.session_summaries (organization_id, computed_at);
CREATE INDEX IF NOT EXISTS idx_summaries_employee_distance
  ON public.session_summaries (organization_id, session_id);

-- admin_sessions
CREATE INDEX IF NOT EXISTS idx_admin_sessions_admin
  ON public.admin_sessions (admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_org_time
  ON public.admin_sessions (organization_id, started_at);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_monitoring_session
  ON public.admin_sessions (admin_id) WHERE ended_at IS NULL;

-- employee_daily_metrics
CREATE INDEX IF NOT EXISTS idx_emp_daily_org_date
  ON public.employee_daily_metrics (organization_id, date);
CREATE INDEX IF NOT EXISTS idx_emp_daily_employee_date
  ON public.employee_daily_metrics (employee_id, date);
CREATE INDEX IF NOT EXISTS idx_emp_daily_org_distance
  ON public.employee_daily_metrics (organization_id, distance_km DESC);

-- org_daily_metrics
CREATE INDEX IF NOT EXISTS idx_org_daily_org_date
  ON public.org_daily_metrics (organization_id, date);

-- employee_latest_sessions
CREATE INDEX IF NOT EXISTS idx_latest_sessions_org
  ON public.employee_latest_sessions (organization_id);
CREATE INDEX IF NOT EXISTS idx_latest_sessions_status
  ON public.employee_latest_sessions (status);
CREATE INDEX IF NOT EXISTS idx_latest_sessions_updated
  ON public.employee_latest_sessions (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_latest_sessions_org_status
  ON public.employee_latest_sessions (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_latest_sessions_org_status_updated
  ON public.employee_latest_sessions (organization_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_latest_sessions_active
  ON public.employee_latest_sessions (organization_id) WHERE status = 'ACTIVE';
-- Live DB extra: FK support for session lookups
CREATE INDEX IF NOT EXISTS idx_latest_sessions_session_id
  ON public.employee_latest_sessions (session_id);

-- webhooks
CREATE INDEX IF NOT EXISTS idx_webhooks_organization_id
  ON public.webhooks (organization_id);
-- GIN index for fast event-type filtering on active webhooks (fanout queries)
CREATE INDEX IF NOT EXISTS idx_webhooks_events_gin_active
  ON public.webhooks USING GIN (events) WHERE is_active = true;
-- Covering index: avoids heap fetch for the webhook fanout hot path
CREATE INDEX IF NOT EXISTS idx_webhooks_fanout_covering
  ON public.webhooks (organization_id) INCLUDE (id, url, secret) WHERE is_active = true;

-- webhook_deliveries
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_event_id
  ON public.webhook_deliveries (event_id);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_webhook_delivered_at
  ON public.webhook_deliveries (webhook_id, delivered_at DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_org_delivered_at
  ON public.webhook_deliveries (organization_id, delivered_at DESC);
-- Partial index: only rows that need retry processing
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_pending_retry
  ON public.webhook_deliveries (next_retry_at)
  WHERE status = 'pending' AND next_retry_at IS NOT NULL;

-- queue_retry_intents
CREATE INDEX IF NOT EXISTS idx_queue_retry_intents_queue_status
  ON public.queue_retry_intents (queue_name, status);
CREATE INDEX IF NOT EXISTS idx_queue_retry_intents_status_next_retry
  ON public.queue_retry_intents (status, next_retry_at);
CREATE INDEX IF NOT EXISTS idx_queue_retry_intents_status_created_at
  ON public.queue_retry_intents (status, created_at);

-- ══════════════════════════════════════════════════════════════
-- FUNCTIONS
-- ══════════════════════════════════════════════════════════════

-- Generic updated_at stamper
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.set_updated_at() IS
  'Generic updated_at stamper. Attach as BEFORE UPDATE trigger to any table with updated_at.';

-- ── fn_auto_create_employee ──────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_auto_create_employee()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code    TEXT;
  v_seq_num BIGINT;
BEGIN
  -- Phase 27b: only create an employee record for EMPLOYEE role users.
  -- ADMIN users are org managers and must not participate in attendance or expenses.
  IF NEW.role <> 'EMPLOYEE' THEN
    RETURN NEW;
  END IF;

  v_seq_num := nextval('public.employee_code_seq');
  v_code    := 'EMP' || LPAD(v_seq_num::text, 4, '0');

  INSERT INTO public.employees (
    id, organization_id, user_id, name, phone,
    employee_code, is_active, last_activity_at, created_at, updated_at
  ) VALUES (
    gen_random_uuid(),
    NEW.organization_id,
    NEW.id,
    initcap(replace(split_part(NEW.email, '@', 1), '.', ' ')),
    NULL,
    v_code,
    true,
    NULL,
    now(),
    now()
  );

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.fn_auto_create_employee() IS
  'Auto-creates employees row on users INSERT for EMPLOYEE role only.
   ADMIN users are skipped — they are org managers, not field employees.
   Phase 27b: restricted from ALL users to EMPLOYEE-only.';

-- ── fn_update_employee_latest_session ────────────────────────
CREATE OR REPLACE FUNCTION public.fn_update_employee_latest_session()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Staleness guard: skip if a newer session is already in the snapshot
  IF EXISTS (
    SELECT 1 FROM public.employee_latest_sessions els
    WHERE els.employee_id    = NEW.employee_id
      AND els.latest_checkin > NEW.checkin_at
      AND els.session_id    <> NEW.id
  ) THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.employee_latest_sessions (
    employee_id, organization_id, session_id,
    latest_checkin, latest_checkout,
    total_distance_km, total_duration_seconds,
    status, updated_at
  )
  VALUES (
    NEW.employee_id,
    NEW.organization_id,
    NEW.id,
    NEW.checkin_at,
    NEW.checkout_at,
    NEW.total_distance_km,
    NEW.total_duration_seconds,
    CASE
      WHEN NEW.checkout_at IS NULL                        THEN 'ACTIVE'
      WHEN NEW.checkout_at > now() - interval '24 hours' THEN 'RECENT'
      ELSE                                                     'INACTIVE'
    END,
    now()
  )
  ON CONFLICT (employee_id) DO UPDATE SET
    session_id             = EXCLUDED.session_id,
    organization_id        = EXCLUDED.organization_id,
    latest_checkin         = EXCLUDED.latest_checkin,
    latest_checkout        = EXCLUDED.latest_checkout,
    total_distance_km      = EXCLUDED.total_distance_km,
    total_duration_seconds = EXCLUDED.total_duration_seconds,
    status                 = EXCLUDED.status,
    updated_at             = now();

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.fn_update_employee_latest_session() IS
  'Maintains employee_latest_sessions snapshot on every attendance_sessions change.
   Staleness guard prevents old sessions from overwriting recent ones.';

-- ── fn_sync_summary_to_latest_session ────────────────────────
CREATE OR REPLACE FUNCTION public.fn_sync_summary_to_latest_session()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.employee_latest_sessions els
  SET
    total_distance_km      = NEW.total_distance_km,
    total_duration_seconds = NEW.total_duration_seconds,
    updated_at             = now()
  FROM public.attendance_sessions s
  WHERE s.id            = NEW.session_id
    AND els.employee_id = s.employee_id
    AND els.session_id  = NEW.session_id;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.fn_sync_summary_to_latest_session() IS
  'Patches distance/duration into employee_latest_sessions when session_summaries changes.
   Only applies if the summary belongs to the employee''s current latest session.';

-- ── generate_employee_code ────────────────────────────────────
CREATE OR REPLACE FUNCTION public.generate_employee_code(p_prefix TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code    TEXT;
  v_seq_num BIGINT;
BEGIN
  v_seq_num := nextval('public.employee_code_seq');
  v_code    := p_prefix || LPAD(v_seq_num::text, 4, '0');
  RETURN v_code;
END;
$$;

COMMENT ON FUNCTION public.generate_employee_code(TEXT) IS
  'Generate employee codes with given prefix. Legacy function retained for backward compat.';

-- ── get_org_latest_sessions ──────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_org_latest_sessions(
  p_org_id UUID,
  p_status TEXT    DEFAULT 'all',
  p_limit  INTEGER DEFAULT 20,
  p_offset INTEGER DEFAULT 0
)
RETURNS TABLE (
  id                            UUID,
  employee_id                   UUID,
  organization_id               UUID,
  checkin_at                    TIMESTAMPTZ,
  checkout_at                   TIMESTAMPTZ,
  total_distance_km             FLOAT8,
  total_duration_seconds        INT,
  distance_recalculation_status TEXT,
  created_at                    TIMESTAMPTZ,
  updated_at                    TIMESTAMPTZ,
  employee_code                 TEXT,
  employee_name                 TEXT,
  activity_status               TEXT,
  total_count                   BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  WITH latest AS (
    SELECT DISTINCT ON (s.employee_id)
      s.id, s.employee_id, s.organization_id,
      s.checkin_at, s.checkout_at,
      s.total_distance_km, s.total_duration_seconds,
      s.distance_recalculation_status::TEXT,
      s.created_at, s.updated_at,
      e.employee_code,
      e.name AS employee_name,
      CASE
        WHEN s.checkout_at IS NULL                        THEN 'ACTIVE'
        WHEN s.checkout_at > NOW() - INTERVAL '24 hours' THEN 'RECENT'
        ELSE                                                   'INACTIVE'
      END AS activity_status
    FROM attendance_sessions s
    JOIN employees e ON e.id = s.employee_id
    WHERE s.organization_id = p_org_id
    ORDER BY s.employee_id, s.checkin_at DESC
  ),
  filtered AS (
    SELECT * FROM latest
    WHERE
      p_status = 'all'
      OR (p_status = 'active'   AND activity_status = 'ACTIVE')
      OR (p_status = 'recent'   AND activity_status = 'RECENT')
      OR (p_status = 'inactive' AND activity_status = 'INACTIVE')
  ),
  counted AS (
    SELECT *, COUNT(*) OVER() AS total_count
    FROM filtered
    ORDER BY
      CASE activity_status
        WHEN 'ACTIVE'  THEN 1
        WHEN 'RECENT'  THEN 2
        ELSE                3
      END,
      checkin_at DESC
  )
  SELECT * FROM counted
  LIMIT p_limit OFFSET p_offset;
END;
$$;

COMMENT ON FUNCTION public.get_org_latest_sessions(UUID, TEXT, INTEGER, INTEGER) IS
  'Paginated admin sessions dashboard query. p_status: all | active | recent | inactive';

-- ── get_active_map_markers ───────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_active_map_markers(
  p_org_id uuid,
  p_limit  integer DEFAULT 1000
)
RETURNS TABLE (
  employee_id   uuid,
  latitude      double precision,
  longitude     double precision,
  recorded_at   timestamptz,
  employee_name text,
  employee_code text,
  status        text,
  session_id    uuid
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT DISTINCT ON (g.employee_id)
    g.employee_id,
    g.latitude,
    g.longitude,
    g.recorded_at,
    e.name          AS employee_name,
    e.employee_code,
    els.status,
    els.session_id
  FROM gps_locations g
  JOIN employee_latest_sessions els
    ON  els.employee_id     = g.employee_id
    AND els.organization_id = p_org_id
    AND els.status IN ('ACTIVE', 'RECENT')
  JOIN employees e ON e.id = g.employee_id
  WHERE g.organization_id = p_org_id
  ORDER BY g.employee_id, g.recorded_at DESC
  LIMIT p_limit;
$$;

-- ── increment_employee_session_metrics ────────────────────────
CREATE OR REPLACE FUNCTION public.increment_employee_session_metrics(
  p_employee_id UUID,
  p_org_id      UUID,
  p_date        DATE,
  p_distance    FLOAT8,
  p_duration    INT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.employee_daily_metrics (
    employee_id, organization_id, date,
    sessions, distance_km, duration_seconds,
    created_at, updated_at
  ) VALUES (
    p_employee_id, p_org_id, p_date,
    1, p_distance, p_duration,
    now(), now()
  )
  ON CONFLICT (employee_id, date) DO UPDATE SET
    sessions         = employee_daily_metrics.sessions + 1,
    distance_km      = employee_daily_metrics.distance_km + EXCLUDED.distance_km,
    duration_seconds = employee_daily_metrics.duration_seconds + EXCLUDED.duration_seconds,
    updated_at       = now();
END;
$$;

COMMENT ON FUNCTION public.increment_employee_session_metrics(UUID, UUID, DATE, FLOAT8, INT) IS
  'Atomically increment daily metrics on checkout.';

-- ── increment_employee_expense_metrics ────────────────────────
CREATE OR REPLACE FUNCTION public.increment_employee_expense_metrics(
  p_employee_id UUID,
  p_org_id      UUID,
  p_date        DATE,
  p_amount      NUMERIC
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.employee_daily_metrics (
    employee_id, organization_id, date,
    sessions, distance_km, duration_seconds, expenses_count, expenses_amount,
    created_at, updated_at
  ) VALUES (
    p_employee_id, p_org_id, p_date,
    0, 0, 0, 1, p_amount,
    now(), now()
  )
  ON CONFLICT (employee_id, date) DO UPDATE SET
    expenses_count  = employee_daily_metrics.expenses_count + 1,
    expenses_amount = employee_daily_metrics.expenses_amount + EXCLUDED.expenses_amount,
    updated_at      = now();
END;
$$;

COMMENT ON FUNCTION public.increment_employee_expense_metrics(UUID, UUID, DATE, NUMERIC) IS
  'Atomically increment expense metrics on submission.';

-- ── increment_org_session_metrics ─────────────────────────────
CREATE OR REPLACE FUNCTION public.increment_org_session_metrics(
  p_org_id   UUID,
  p_date     DATE,
  p_distance FLOAT8,
  p_duration INT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.org_daily_metrics (
    organization_id, date,
    total_sessions, total_distance_km, total_duration_seconds,
    created_at, updated_at
  ) VALUES (
    p_org_id, p_date,
    1, p_distance, p_duration,
    now(), now()
  )
  ON CONFLICT (organization_id, date) DO UPDATE SET
    total_sessions         = org_daily_metrics.total_sessions + 1,
    total_distance_km      = org_daily_metrics.total_distance_km + EXCLUDED.total_distance_km,
    total_duration_seconds = org_daily_metrics.total_duration_seconds + EXCLUDED.total_duration_seconds,
    updated_at             = now();
END;
$$;

COMMENT ON FUNCTION public.increment_org_session_metrics(UUID, DATE, FLOAT8, INT) IS
  'Atomically increment org-level daily metrics on checkout.';

-- ── custom_access_token_hook ─────────────────────────────────
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role        public.user_role;
  v_employee_id UUID;
  v_org_id      UUID;
BEGIN
  SELECT role, id, organization_id INTO v_role, v_employee_id, v_org_id
  FROM public.users
  WHERE id = (event->>'sub')::uuid
  LIMIT 1;

  IF v_role IS NULL THEN
    RETURN event;
  END IF;

  event := jsonb_set(event, '{claims,role}',   to_jsonb(v_role::text));
  event := jsonb_set(event, '{claims,org_id}', to_jsonb(v_org_id));

  IF v_role = 'EMPLOYEE' THEN
    SELECT id INTO v_employee_id
    FROM public.employees
    WHERE user_id = (event->>'sub')::uuid
    LIMIT 1;

    IF v_employee_id IS NOT NULL THEN
      event := jsonb_set(event, '{claims,employee_id}', to_jsonb(v_employee_id));
    END IF;
  END IF;

  RETURN event;
END;
$$;

COMMENT ON FUNCTION public.custom_access_token_hook(JSONB) IS
  'Supabase Auth hook to inject custom claims (role, org_id, employee_id) into JWT.';

-- ══════════════════════════════════════════════════════════════
-- TRIGGERS
-- ══════════════════════════════════════════════════════════════

CREATE TRIGGER trg_updated_at_organizations
  BEFORE UPDATE ON public.organizations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_users
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_employees
  BEFORE UPDATE ON public.employees
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_sessions
  BEFORE UPDATE ON public.attendance_sessions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_expenses
  BEFORE UPDATE ON public.expenses
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_updated_at_summaries
  BEFORE UPDATE ON public.session_summaries
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_auto_create_employee
  AFTER INSERT ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.fn_auto_create_employee();

CREATE TRIGGER trg_update_employee_latest_session
  AFTER INSERT OR UPDATE OF checkin_at, checkout_at, total_distance_km, total_duration_seconds
  ON public.attendance_sessions
  FOR EACH ROW EXECUTE FUNCTION public.fn_update_employee_latest_session();

CREATE TRIGGER trg_sync_summary_to_latest_session
  AFTER INSERT OR UPDATE OF total_distance_km, total_duration_seconds
  ON public.session_summaries
  FOR EACH ROW EXECUTE FUNCTION public.fn_sync_summary_to_latest_session();

-- ══════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ══════════════════════════════════════════════════════════════

ALTER TABLE public.organizations           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_sessions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gps_locations           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_summaries       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_sessions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_daily_metrics  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_daily_metrics       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_latest_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhooks                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_deliveries      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.queue_retry_intents     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_dashboard_snapshot  ENABLE ROW LEVEL SECURITY;

-- ── RLS design notes ──────────────────────────────────────────
--
-- Pattern A — simple org isolation (single subquery):
--   USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()))
--
-- Pattern B — role-aware admin policies (single subquery, both fields):
--   Each admin policy does ONE lookup into public.users to get both
--   organization_id AND role simultaneously, avoiding duplicate subqueries.
--   Postgres caches correlated subqueries per row so this is planner-friendly.
--
-- Pattern C — employee self-access (single subquery into employees):
--   USING (employee_id = (SELECT id FROM public.employees WHERE user_id = auth.uid()))
--
-- auth.uid() is called directly — no (SELECT auth.uid()) wrapper needed.
-- The wrapper was a historic Supabase workaround; auth.uid() is now inlined
-- as a stable function and handled correctly by the planner.

-- ── Org isolation policies ─────────────────────────────────────

CREATE POLICY "org_isolation_organizations"
  ON public.organizations FOR ALL
  USING (id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_users"
  ON public.users FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_admin_sessions"
  ON public.admin_sessions FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_org_daily_metrics"
  ON public.org_daily_metrics FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

CREATE POLICY "org_isolation_webhooks"
  ON public.webhooks FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

-- queue_retry_intents: service_role only — BullMQ worker accesses via service_role key.
-- TO service_role means authenticated users get zero rows (RLS still enabled).
CREATE POLICY "service_role_only_queue_retry_intents"
  ON public.queue_retry_intents
  TO service_role
  USING (true)
  WITH CHECK (true);

-- webhook_deliveries: service_role only — written/read by the webhook worker, never by clients.
CREATE POLICY "org_isolation_webhook_deliveries"
  ON public.webhook_deliveries
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "org_isolation_org_dashboard_snapshot"
  ON public.org_dashboard_snapshot FOR ALL
  USING (organization_id = (SELECT organization_id FROM public.users WHERE id = auth.uid()));

-- ── Phase 27a: Role-aware RLS (split admin_all + employee_self) ─
--
-- Admin policies: single subquery per policy fetches org_id + role together.
-- Employee policies: single subquery into employees for their own id.

-- EXPENSES
CREATE POLICY "expenses_admin_all" ON public.expenses
  FOR ALL TO authenticated
  USING (
    (SELECT organization_id = expenses.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  )
  WITH CHECK (
    (SELECT organization_id = expenses.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  );

CREATE POLICY "expenses_employee_self" ON public.expenses
  FOR ALL TO authenticated
  USING (employee_id    = (SELECT id FROM public.employees WHERE user_id = auth.uid()))
  WITH CHECK (employee_id = (SELECT id FROM public.employees WHERE user_id = auth.uid()));

-- ATTENDANCE_SESSIONS
CREATE POLICY "attendance_sessions_admin_all" ON public.attendance_sessions
  FOR ALL TO authenticated
  USING (
    (SELECT organization_id = attendance_sessions.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  )
  WITH CHECK (
    (SELECT organization_id = attendance_sessions.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  );

CREATE POLICY "attendance_sessions_employee_self" ON public.attendance_sessions
  FOR ALL TO authenticated
  USING (employee_id    = (SELECT id FROM public.employees WHERE user_id = auth.uid()))
  WITH CHECK (employee_id = (SELECT id FROM public.employees WHERE user_id = auth.uid()));

-- GPS_LOCATIONS
CREATE POLICY "gps_locations_admin_all" ON public.gps_locations
  FOR ALL TO authenticated
  USING (
    (SELECT organization_id = gps_locations.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  )
  WITH CHECK (
    (SELECT organization_id = gps_locations.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  );

CREATE POLICY "gps_locations_employee_self" ON public.gps_locations
  FOR ALL TO authenticated
  USING (employee_id    = (SELECT id FROM public.employees WHERE user_id = auth.uid()))
  WITH CHECK (employee_id = (SELECT id FROM public.employees WHERE user_id = auth.uid()));

-- EMPLOYEE_DAILY_METRICS
CREATE POLICY "employee_daily_metrics_admin_all" ON public.employee_daily_metrics
  FOR ALL TO authenticated
  USING (
    (SELECT organization_id = employee_daily_metrics.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  )
  WITH CHECK (
    (SELECT organization_id = employee_daily_metrics.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  );

CREATE POLICY "employee_daily_metrics_employee_self" ON public.employee_daily_metrics
  FOR ALL TO authenticated
  USING (employee_id    = (SELECT id FROM public.employees WHERE user_id = auth.uid()))
  WITH CHECK (employee_id = (SELECT id FROM public.employees WHERE user_id = auth.uid()));

-- SESSION_SUMMARIES
CREATE POLICY "session_summaries_admin_all" ON public.session_summaries
  FOR ALL TO authenticated
  USING (
    (SELECT organization_id = session_summaries.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  )
  WITH CHECK (
    (SELECT organization_id = session_summaries.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  );

CREATE POLICY "session_summaries_employee_self" ON public.session_summaries
  FOR SELECT TO authenticated
  USING (
    session_id IN (
      SELECT id FROM public.attendance_sessions
      WHERE employee_id = (SELECT id FROM public.employees WHERE user_id = auth.uid())
    )
  );

-- EMPLOYEES
CREATE POLICY "employees_admin_all" ON public.employees
  FOR ALL TO authenticated
  USING (
    (SELECT organization_id = employees.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  )
  WITH CHECK (
    (SELECT organization_id = employees.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  );

CREATE POLICY "employees_employee_self" ON public.employees
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- EMPLOYEE_LATEST_SESSIONS
CREATE POLICY "els_admin_all" ON public.employee_latest_sessions
  FOR ALL TO authenticated
  USING (
    (SELECT organization_id = employee_latest_sessions.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  )
  WITH CHECK (
    (SELECT organization_id = employee_latest_sessions.organization_id AND role = 'ADMIN'
     FROM public.users WHERE id = auth.uid())
  );

CREATE POLICY "els_employee_self" ON public.employee_latest_sessions
  FOR SELECT TO authenticated
  USING (employee_id = (SELECT id FROM public.employees WHERE user_id = auth.uid()));

-- ══════════════════════════════════════════════════════════════
-- GRANTS
-- ══════════════════════════════════════════════════════════════

-- Allow authenticated users to call all public RPC functions.
-- Without this, PostgREST RPC calls (e.g. get_org_latest_sessions,
-- get_active_map_markers) fail silently with 404 or permission denied.
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

-- ══════════════════════════════════════════════════════════════
-- CRON JOBS
-- ══════════════════════════════════════════════════════════════

DO $outer$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM cron.job WHERE jobname = 'employee-status-refresh'
  ) THEN
    PERFORM cron.schedule(
      'employee-status-refresh',
      '0 * * * *',
      $cron$
        UPDATE public.employee_latest_sessions
        SET
          status     = 'INACTIVE',
          updated_at = now()
        WHERE status          = 'RECENT'
          AND latest_checkout < now() - interval '24 hours';
      $cron$
    );
  END IF;
END;
$outer$;

-- ══════════════════════════════════════════════════════════════
-- SCHEMA COMPLETE
-- ══════════════════════════════════════════════════════════════
-- Baseline schema migration for FieldTrack 2.0 (Phase 28 / 2026-03-25)
-- Ground-truthed against live Supabase project nvezwhasasykwnnblokk
--
-- Tables:             15 core
-- Enums:              3
-- Sequences:          1
-- Indexes:            ~60 (including partial, unique, GIN, covering)
-- Functions:          11
-- Triggers:           9
-- RLS Policies:       22 across 15 tables
-- Grants:             1 (authenticated → all public functions)
-- Extensions:         4 (uuid-ossp, pgcrypto, pg_cron, pg_stat_statements)
-- Cron Jobs:          1 (employee-status-refresh)
--
-- ── Changes vs Phase 27b document ─────────────────────────────
--
-- queue_retry_intents:
--   BREAKING — job_id + max_retries removed; job_key + payload + status added
--   Unique constraint: (queue_name, job_id) → (queue_name, job_key)
--
-- webhook_deliveries:
--   BREAKING — status_code / response / error replaced by
--   status TEXT / response_status INT / response_body TEXT / last_error TEXT
--   Added: organization_id, event_id (idempotency), delivered_at
--   Removed: updated_at
--   Unique constraint added: (event_id, webhook_id)
--
-- webhooks:
--   updated_at removed; column order adjusted (secret before events)
--
-- org_dashboard_snapshot:
--   BREAKING — id UUID removed; organization_id is now the PK
--   All columns redesigned: status counts, today metrics, pending expenses
--
-- employees:
--   Column order cosmetically different (employee_code + last_activity_at
--   were added via ALTER in earlier migrations)
--
-- Indexes (live DB extras vs doc):
--   idx_latest_sessions_session_id, idx_expenses_reviewed_by,
--   idx_webhooks_events_gin_active (GIN), idx_webhooks_fanout_covering,
--   idx_webhook_deliveries_* (4), idx_queue_retry_intents_* (3)
--
-- ── Security & correctness fixes (2026-03-25 review) ──────────
--
-- Fix 1 — CONCURRENTLY removed from idx_gps_locations_session_recorded_at
--   CREATE INDEX CONCURRENTLY is not allowed inside transactions.
--   Supabase runs migrations inside transactions → use plain CREATE INDEX.
--
-- Fix 2 — USING (true) policies tightened to TO service_role
--   queue_retry_intents + webhook_deliveries now explicitly scoped to
--   service_role. Previously USING (true) with no role restriction gave
--   every authenticated user full unrestricted access.
--
-- Fix 3 — (SELECT auth.uid()) nesting removed throughout
--   auth.uid() is a stable inlined function; the SELECT wrapper adds
--   unnecessary subquery overhead and was a Supabase legacy workaround.
--
-- Fix 4 — Dual subquery pattern collapsed in admin_all RLS policies
--   Old pattern fetched organization_id and role via two separate subqueries
--   per row. New pattern does one lookup returning both fields as a boolean
--   expression, halving user table reads in RLS evaluation.
--
-- Fix 5 — GRANT EXECUTE added for authenticated role
--   Without this, PostgREST RPC calls silently fail with 404.
--   Applies to: get_org_latest_sessions, get_active_map_markers, and all
--   increment_* metrics functions called from the API layer.
--
-- Fix 6 — webhooks.secret plain-text storage documented
--   Column retained as-is to match live DB. Flagged for future migration
--   to Supabase Vault or hashed storage.
-- ══════════════════════════════════════════════════════════════